### ISSUE TITLE
Question on how it works

### ISSUE THREAD

**Issue by MGlaab** [cognitivegears/CircuitPython_Schedule#1]
I just have a question on how this works. I'd like to use the schedule.every().day.at("specific time").do(greet) with just a raspberry pi pico running CircuitPython with no external hardware. How would the board get the time? Is a RTC required to use schedule that way? Is the time set in the python file?

**Comment by dhalbert** [comment]
You need an external time source, whether manual or some RTC. The Pico has no idea what time it is when it starts up. Further discussion in discord.

**Comment by MGlaab** [comment]
Thanks Dan. I was just talking to you on Discord.

**Comment by cognitivegears** [comment]
One other thought, though not something I've played with myself yet. If you look at the [RTC Example](https://github.com/cognitivegears/CircuitPython_Schedule/blob/main/examples/circuitpython_schedule_rtc.py), the most important bit is the following:

`rtc.RTC().datetime = rtc_device.datetime`

This is just setting the micro-controller's date time to the real time clock device. Instead, it should be perfectly reasonable to use network time protocol instead if you have a network stack (i.e. ESP32.) Might or might not be helpful to you depending on what you already are using for your project.

**Comment by cognitivegears** [comment]
It looks like the question has been answered, please re-open if additional help is needed.

**Comment by natcl** [comment]
I have a related question,
I have an ESP32 with no RTC and I use NTP to set the time, it seems to work well for a couple of days but at some point the timers fail to start, even though I resync with ntp every hour, any idea of what could cause this issue ?
here's my code:
https://gist.github.com/natcl/a0e8000327e9b9e8219d1986720edc4d

**Comment by cognitivegears** [comment]
> I have a related question, I have an ESP32 with no RTC and I use NTP to set the time, it seems to work well for a couple of days but at some point the timers fail to start, even though I resync with ntp every hour, any idea of what could cause this issue ? here's my code: https://gist.github.com/natcl/a0e8000327e9b9e8219d1986720edc4d

I have to admit, it's been a minute since I've used this code myself on a ESP32. However, looking a your gist, I have a couple of things you might want to try:

First, in `update_time()`, I believe you should use a try / except block for ValueError and OSError - from the NTP source it looks like these can be raised if it fails to get the time, for example if there is a break in the Wifi connection (the CircuitPython code itself isn't always great about error handling from what I've seen and is a bit "optimistic".) Those ESP32 wifi connections aren't always the strongest, it might be that it's losing signal every once in a while or some other connection problem. Maybe an except block that recreates the `pool` would be appropriate here, I don't see anything in their code that handles it if the current pool because invalid. Also, just in general I think I'd make sure that I have a valid time before I overwrite the current time with `rtc.datetime = time.struct_time(ntp.datetime)`, probably better to have an old date than an incorrect one. I'm not totally sure what the appropriate thing to check here, maybe that it's not equal to the epoch, or maybe even better that it is just >= 2024 before you set it, though that's a bit of a guess on my part.

Are you seeing the print statements after that time (if you still have it hooked up to a serial monitor?) - that might help determine whether it has crashed or gotten a bad time, etc.

All of that is not to say that there couldn't be an issue in CircuitPython_Schedule itself, that is certainly possible as well - these just seem like "low-hanging fruit" to check since network operations are not always reliable. If these don't help, please let me know and we can dig into it further also.

**Comment by natcl** [comment]
Thanks a lot for your tips !
Good idea to add some try statements and validate the date is ok, will try this first. 

I need to figure out better debugging, I'm used to wired Arduino/Teensy and from what I understand CircruitPython with the ESP32 works only via WIFI so I might setup a computer to monitor for a couple of days.
It doesn't seem to crash completely as the buttons are setup to light the keys and that still works.

Will let you know if I find something, thanks again !

**Comment by cognitivegears** [comment]
> Thanks a lot for your tips ! Good idea to add some try statements and validate the date is ok, will try this first.
> 
> I need to figure out better debugging, I'm used to wired Arduino/Teensy and from what I understand CircruitPython with the ESP32 works only via WIFI so I might setup a computer to monitor for a couple of days. It doesn't seem to crash completely as the buttons are setup to light the keys and that still works.
> 
> Will let you know if I find something, thanks again !

Awesome, please let me know how it goes!
